>## Task 10

### Exercise 1: Create a simple NumPy array.

In [2]:
import numpy as np 

npArray=np.array([1,2,3,4,5,6,7,8,9,10])
npArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Exercise 2: Create a multi-dimensional NumPy array using lists.

In [3]:
data=[[1,2,3,4,5], [6,7,8,9,10]]
npArray=np.array(data)
npArray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Exercise 3a: Create a one-dimensional array containing element '0'.

In [4]:
zeroArray=np.zeros(10)
zeroArray

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Exercise 3b: Create a multi-dimensional array containing element '0'.

In [5]:
zeroArray=np.zeros((2,3))
zeroArray

array([[0., 0., 0.],
       [0., 0., 0.]])

### Exercise 4: Create two arrays with different data types.

In [7]:
npArray1=np.array([1,2,3,4,5], dtype=np.float64)
npArray2=np.array([1,2,3,4,5], dtype=np.int32)
print(npArray1.dtype)
print(npArray2.dtype)

float64
int32


### Exercise 5: Arithmetic with NumPy Arrays.

#### Exercise 5a: Add two arrays.

In [9]:
array=np.array([[1,2,3,4,5],[6,7,8,9,10]])
array+array

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

#### Exercise 5b: Subtract two arrays.

In [10]:
array-array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

#### Exercise 5c: Multiply two arrays.

In [11]:
array*array

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

#### Exercise 5d: Divide two arrays.

In [12]:
array/array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### Exercise 5e: Scalars and NumPy Arrays.

In [13]:
1/array

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ]])

In [14]:
array**2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

#### Exercise 5f: Comparison of NumPy Arrays.

In [15]:
array2=np.array([[5,4,3,2,1],[10, 9, 8, 7, 6]])

array>array2

array([[False, False, False,  True,  True],
       [False, False, False,  True,  True]])